import ENVIRONMENT from './ENVIRONMENT.js';
import HTTP_HEADER from './HTTP_HEADER.js';
import HTTP_METHOD from './HTTP_METHOD.js';
import HTTP_STATUS_CODE from './HTTP_STATUS_CODE.js';
import MEDIA_TYPE from './MEDIA_TYPE.js';


const ENUMERATIONS = Object.freeze({
  ENVIRONMENT: ENVIRONMENT,
  HTTP_HEADER: HTTP_HEADER,
  HTTP_METHOD: HTTP_METHOD,
  HTTP_STATUS_CODE: HTTP_STATUS_CODE,
  MEDIA_TYPE: MEDIA_TYPE
});


export default ENUMERATIONS;