import ava from 'ava';

import REFERENCE from '../REFERENCE.js';


ava(
  'core.webUtilities.indexedDB.REFERENCE',
  (test) => {
    test.is(typeof REFERENCE, 'object');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES, 'object');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.DATABASE, 'object');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.DATABASE.ABORT, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.DATABASE.CLOSE, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.DATABASE.ERROR, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.DATABASE.VERSIONCHANGE, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.OPEN_DB_REQUEST, 'object');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.OPEN_DB_REQUEST.BLOCKED, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.OPEN_DB_REQUEST.ERROR, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.OPEN_DB_REQUEST.SUCCESS, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.OPEN_DB_REQUEST.UPGRADENEEDED, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.REQUEST, 'object');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.REQUEST.ERROR, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.REQUEST.SUCCESS, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.TRANSACTION, 'object');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.TRANSACTION.ABORT, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.TRANSACTION.COMPLETE, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.EVENT_TYPES.TRANSACTION.ERROR, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.REQUEST_READY_STATES, 'object');
    test.is(typeof REFERENCE.ENUMERATIONS.REQUEST_READY_STATES.DONE, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.REQUEST_READY_STATES.PENDING, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.TRANSACTION_MODES, 'object');
    test.is(typeof REFERENCE.ENUMERATIONS.TRANSACTION_MODES.READONLY, 'string');
    test.is(typeof REFERENCE.ENUMERATIONS.TRANSACTION_MODES.READWRITE, 'string');
  }
);